
- name: mongo shell command 
  shell: mongo --eval "rs.initiate()"

- name: shell wait 
  shell: sleep 30 

- name: Create the file to initialize the replicaset
  template: src=repset_init.j2 dest=/tmp/repset2_init.js

- name: Initialize the replication set on the primary
  shell: /usr/bin/mongo /tmp/repset2_init.js
  args:
    creates: initiateReplicaset
